### ISSUE TITLE
'cannot call wasm-bindgen imported functions on non-wasm targets'

### ISSUE THREAD

**Issue by jayjayhust** [AleoHQ/workshop#24]
While executing the installation script, I came across a issue listed below:
 
<img width="1279" alt="aleo workshop install error" src="https://user-images.githubusercontent.com/78330209/219580149-6e6ad967-97cd-4341-9150-c3bbb3289a60.png">

`thread 'main' panicked at 'cannot call wasm-bindgen imported functions on non-wasm targets', /home/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.61/src/lib.rs:5604:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

Can anyone give a suggestion on this error? thx a lot.

**Comment by howardwu** [comment]
Thanks for flagging this! We had an outage that should be fixed now. Feel free to close the issue if it is working now.

**Comment by jayjayhust** [comment]
> Thanks for flagging this! We had an outage that should be fixed now. Feel free to close the issue if it is working now.

Yeah it works now.  Probably my network problem. Thanks a lot for ur reply.
<img width="1279" alt="install ok" src="https://user-images.githubusercontent.com/78330209/221982603-ac835e56-2f08-4362-a750-ccb112f39bfd.png">
