### ISSUE TITLE
Please explain why pid input and group has to be such a high number? 

### ISSUE THREAD

**Issue by DylanCkawalec** [AleoHQ/workshop#30]
When comparing the pid to the vote program, it's not known why the pid and the _nonce...group has to be such an absurdly high number. Trying to understand what pid is, and why it's so high in this example. 
<img width="720" alt="Screenshot 2023-05-09 at 4 14 28 PM" src="https://github.com/AleoHQ/workshop/assets/43707795/ac029ff7-a66e-44a2-97a4-6035ff02b187">

**Comment by howardwu** [comment]
These values are `field` and `group` types. In this case, these are the output of hashes, and as such, are the digest of the inputs that composed them. You can find more information on these types in the developer docs: https://developer.aleo.org/leo/language#field-elements
