### ISSUE TITLE
Requirements for a full node?

### ISSUE THREAD

**Issue by ally9335** [AleoHQ/workshop#34]
What the requirements for a full node, hardware-wise?

What's the size in Gb of the blockchain?

**Comment by ally9335** [comment]
@howardwu up

**Comment by ally9335** [comment]
@collinc97 up

**Comment by howardwu** [comment]
The specifications for a full-node are detailed in the snarkOS README: https://github.com/AleoHQ/snarkOS/

**Comment by ally9335** [comment]
The current size of the blockchain isn't mentioned @howardwu 
The "storage" is, but is it necessarily equal to it, and as of now?
